#!/usr/bin/env node
/**
 * Generate favicons, app icons, and site.webmanifest from a single source image.
 *
 * Drop either brand/icon.svg or brand/icon.png (prefer SVG), then run:
 *   npm run icons
 *
 * Manifest fields default from brand/icons.config.json, then src/_data/site.js.
 * Override any of them in brand/icons.config.json for this project.
 */

import { mkdir, readdir, readFile, writeFile, copyFile } from "node:fs/promises";
import path from "node:path";
import { createRequire } from "node:module";
import { fileURLToPath } from "node:url";

const __dirname = path.dirname(fileURLToPath(import.meta.url));
const root = path.resolve(__dirname, "..");
const require = createRequire(import.meta.url);

const DEFAULTS = {
  inputDir: "brand",
  outputDir: "src/assets/icons",
  publicPath: "/assets/icons",
  inputNames: ["icon.svg", "icon.png", "icon.jpg", "icon.jpeg", "icon.webp"],
  sizes: [
    { size: 16, file: "favicon-16.png" },
    { size: 32, file: "favicon-32.png" },
    { size: 180, file: "apple-touch-icon.png" },
    { size: 192, file: "icon-192.png" },
    { size: 512, file: "icon-512.png" },
  ],
  manifest: {
    name: null,
    short_name: null,
    description: null,
    start_url: "/",
    display: "browser",
    background_color: "#ffffff",
    theme_color: "#0b0c0c",
  },
};

async function loadJson(filePath) {
  try {
    return JSON.parse(await readFile(filePath, "utf8"));
  } catch (error) {
    if (error && error.code === "ENOENT") return null;
    throw error;
  }
}

function loadSiteData() {
  try {
    return require(path.join(root, "src/_data/site.js"));
  } catch {
    return {};
  }
}

async function findSource(inputDir, inputNames) {
  const absDir = path.join(root, inputDir);
  let entries = [];
  try {
    entries = await readdir(absDir);
  } catch (error) {
    if (error && error.code === "ENOENT") {
      throw new Error(
        `Input folder not found: ${inputDir}/\nCreate it and add icon.svg or icon.png`
      );
    }
    throw error;
  }

  for (const name of inputNames) {
    if (entries.includes(name)) {
      return path.join(absDir, name);
    }
  }

  throw new Error(
    `No source icon found in ${inputDir}/.\nExpected one of: ${inputNames.join(", ")}`
  );
}

function buildManifest(config, site) {
  const name = config.manifest.name || site.serviceName || site.title || "Web App";
  const shortName =
    config.manifest.short_name ||
    name.split(/\s+/).slice(0, 2).join(" ") ||
    name;
  const description =
    config.manifest.description || site.description || name;
  const publicPath = config.publicPath.replace(/\/$/, "");

  return {
    name,
    short_name: shortName,
    description,
    start_url: config.manifest.start_url,
    display: config.manifest.display,
    background_color: config.manifest.background_color,
    theme_color: config.manifest.theme_color,
    icons: [
      {
        src: `${publicPath}/icon-192.png`,
        sizes: "192x192",
        type: "image/png",
      },
      {
        src: `${publicPath}/icon-512.png`,
        sizes: "512x512",
        type: "image/png",
      },
    ],
  };
}

function htmlSnippet(publicPath) {
  const base = publicPath.replace(/\/$/, "");
  return `<!-- App icons / favicon (generated by npm run icons) -->
<link rel="icon" href="${base}/favicon.ico" sizes="any">
<link rel="icon" href="${base}/favicon.svg" type="image/svg+xml">
<link rel="icon" href="${base}/favicon-32.png" type="image/png" sizes="32x32">
<link rel="apple-touch-icon" href="${base}/apple-touch-icon.png">
<link rel="manifest" href="${base}/site.webmanifest">
<meta name="theme-color" content="THEME_COLOR_PLACEHOLDER">`;
}

async function main() {
  const sharp = (await import("sharp")).default;
  const pngToIco = (await import("png-to-ico")).default;

  const userConfig = (await loadJson(path.join(root, "brand/icons.config.json"))) || {};
  const config = {
    ...DEFAULTS,
    ...userConfig,
    sizes: userConfig.sizes || DEFAULTS.sizes,
    inputNames: userConfig.inputNames || DEFAULTS.inputNames,
    manifest: { ...DEFAULTS.manifest, ...(userConfig.manifest || {}) },
  };

  const site = loadSiteData();
  const sourcePath = await findSource(config.inputDir, config.inputNames);
  const outDir = path.join(root, config.outputDir);
  await mkdir(outDir, { recursive: true });

  console.log(`Source: ${path.relative(root, sourcePath)}`);
  console.log(`Output: ${config.outputDir}/`);

  const pngBuffers = {};
  for (const { size, file } of config.sizes) {
    const buffer = await sharp(sourcePath)
      .resize(size, size, {
        fit: "contain",
        background: { r: 0, g: 0, b: 0, alpha: 0 },
      })
      .png()
      .toBuffer();
    await writeFile(path.join(outDir, file), buffer);
    pngBuffers[size] = buffer;
    console.log(`  wrote ${file}`);
  }

  if (sourcePath.toLowerCase().endsWith(".svg")) {
    await copyFile(sourcePath, path.join(outDir, "favicon.svg"));
    console.log("  wrote favicon.svg");
  } else {
    // Raster-only source: also emit an SVG-less reminder via 32px PNG as primary icon.
    console.log("  (no favicon.svg — source was not SVG)");
  }

  const ico = await pngToIco([pngBuffers[16], pngBuffers[32]]);
  await writeFile(path.join(outDir, "favicon.ico"), ico);
  console.log("  wrote favicon.ico");

  const manifest = buildManifest(config, site);
  await writeFile(
    path.join(outDir, "site.webmanifest"),
    `${JSON.stringify(manifest, null, 2)}\n`
  );
  console.log("  wrote site.webmanifest");

  const snippet = htmlSnippet(config.publicPath).replace(
    "THEME_COLOR_PLACEHOLDER",
    manifest.theme_color
  );

  console.log("\n✓ Icons generated.\n");
  console.log("Add (or confirm) this in your HTML <head>:");
  console.log("────────────────────────────────────────");
  console.log(snippet);
  console.log("────────────────────────────────────────\n");
  console.log(
    "Manifest metadata came from brand/icons.config.json and/or src/_data/site.js."
  );
  console.log(
    "Edit brand/icons.config.json when name, colours, or display mode should differ per project.\n"
  );
}

main().catch((error) => {
  console.error(`\n✗ ${error.message}\n`);
  process.exit(1);
});
